package com.example.projectfinal;

public class calendar {
    public static String question[] ={
            "Q1. It was Sunday on Jan 1, 2006. What was the day of the week Jan 1, 2010?",
            "Q2. What was the day of the week on 28th May, 2006?",
            "Q3. What was the day of the week on 17th June, 1998?",
            "Q4. What will be the day of the week 15th August, 2010?",
            "Q5. Today is Monday. After 61 days, it will be:",
            "Q6. If 6th March, 2005 is Monday, what was the day of the week on 6th March, 2004?",
            "Q7. On what dates of April, 2001 did Wednesday fall?",
            "Q8. How many days are there in x weeks x days?",
            "Q9. The last day of a century cannot be",
            "Q10. On 8th Feb, 2005 it was Tuesday. What was the day of the week on 8th Feb, 2004?",
            "Q11. The calendar for the year 2007 will be the same for the year:",
            "Q12. Which of the following is not a leap year?",
            "Q13. On 8th Dec, 2007 Saturday falls. What day of the week was it on 8th Dec, 2006?",
            "Q14. January 1, 2008 is Tuesday. What day of the week lies on Jan 1, 2009?",
            "Q15. January 1, 2007 was Monday. What day of the week lies on Jan. 1, 2008?",
            "Q16. An accurate clock shows 8 o'clock in the morning. Through how may degrees will the hour hand rotate when the clock shows 2 o'clock in the afternoon?",
            "Q17. The reflex angle between the hands of a clock at 10.25 is:",
            "Q18. A clock is started at noon. By 10 minutes past 5, the hour hand has turned through:",
            "Q19. A watch which gains 5 seconds in 3 minutes was set right at 7 a.m. In the afternoon of the same day, when the watch indicated quarter past 4 o'clock, the true time is:",
            "Q20. How much does a watch lose per day, if its hands coincide every 64 minutes?",
            "Q21. The angle between the minute hand and the hour hand of a clock when the time is 4.20, is:",
            "Q22. At what angle the hands of a clock are inclined at 15 minutes past 5?",
            "Q23. At 3:40, the hour hand and the minute hand of a clock form an angle of:",
            "Q24. How many times are the hands of a clock at right angle in a day?",
            "Q25. The angle between the minute hand and the hour hand of a clock when the time is 8.30, is:",
            "Q26. How many times in a day, are the hands of a clock in straight line but opposite in direction?",
            "Q27. How many times do the hands of a clock coincide in a day?",
            "Q28. How many times in a day, the hands of a clock are straight?",
            "Q29. A watch which gains uniformly is 2 minutes low at noon on Monday and is 4 min. 48 sec fast at 2 p.m. on the following Monday. When was it correct?"
    };
    public static String choices[][]={
            {"Sunday","Saturday","Friday","Wednesday"},
            {"Thursday","Friday","Saturday","Sunday"},
            {"Monday","Tuesday","Wednesday","Thursday"},
            {"Sunday","Monday","Tuesday","Friday"},
            {"Wednesday","Saturday","Tuesday","Thursday"},
            {"Sunday","Saturday","Tuesday","Wednesday"},
            {"1st, 8th, 15th, 22nd, 29th","2nd, 9th, 16th, 23rd, 30th","3rd, 10th, 17th, 24th","4th, 11th, 18th, 25th"},
            {"7x^2","8x","14x","7"},
            {"Monday","Wednesday","Tuesday","Friday"},
            {"Tuesday","Monday","Sunday","Wednesday"},
            {"2014","2016","2017","2018"},
            {"700","800","1200","2000"},
            {"Sunday","Thursday","Tuesday","Friday"},
            {"Monday","Wednesday","Thursday","Sunday"},
            {"Monday","Tuesday","Wednesday","Sunday"},
            {"144°","150°","168°","180°"},
            {"180°","192(1/2)°","195°","197(1/2)°"},
            {"145°","150°","155°","160°"},
            {"59(7/12) min. past 3","4 p.m.","58(7/11) min. past 3","2(3/11) min. past 4"},
            {"32(8/11)min","36(5/11)min","90 min.","96 min."},
            {"0°","10°","5°","20°"},
            {"58(1/2)°","64°","67(1/2)°","72(1/2)°"},
            {"120°","125°","130°","135°"},
            {"22","24","44","48"},
            {"80°","75°","60°","105°"},
            {"20","22","24","48"},
            {"20","21","22","24"},
            {"22","24","44","48"},
            {"2 p.m. on Tuesday","2 p.m. on Wednesday","3 p.m. on Thursday","1 p.m. on Friday"}
    };
    public static String correctAnswer[]={
            "Friday",
            "Sunday",
            "Wednesday",
            "Sunday",
            "Saturday",
            "Sunday",
            "4th, 11th, 18th, 25th",
            "8x",
            "Tuesday",
            "Sunday",
            "2018",
            "700",
            "Friday",
            "Thursday",
            "Tuesday",
            "180°",
            "197(1/2)°",
            "155°",
            "4 p.m.",
            "32(8/11)min",
            "10°",
            "67(1/2)°",
            "130°",
            "44",
            "75°",
            "22",
            "22",
            "44",
            "2 p.m. on Wednesday"
    };
}
