package com.example.projectfinal;

public class mockQuestionAnswer4 {
    public static String question[]={
            "Q1. Which of the following is not considered to be a basic element of an enterprise-class database system?",
            "Q2. You can add a row using SQL in a database with which of the following?",
            "Q3. SQL provides five built-in functions: COUNT, SUM, AVG, MAX, MIN.",
            "Q4. The reports generated by a reporting system are usually not delivered in which of the following media?",
            "Q5. The use of packaged data models can offer which of the following benefits?",
            "Q6. Sequential retrieval on a primary key for sequential file storage has which of the following features?",
            "Q7. A UNION query is which of the following?",
            "Q8. A characteristic of a file server is which of the following?",
            "Q9. Data in operational systems are typically fragmented and inconsistent.",
            "Q10. The object definition language (ODL) is which of the following?"

    };
    public static String choices[][]={
            {"Users","Database applications","DBMS","COBOL programs"},
            {"ADD","CREATE","INSERT","MAKE"},
            {"True","False","",""},
            {"Web portal","Commercial courier service","Digital dashboard","E-Mail"},
            {"A. Reduce implementation time and costs","B. Higher quality models","Both A and B.","Neither A nor B."},
            {"Very fast","Moderately fast","Slow","Impractical"},
            {"Combines the output from no more than two queries and must include the same number of columns.","Combines the output from no more than two queries and does not include the same number of columns.","Combines the output from multiple queries and must include the same number of columns.","Combines the output from multiple queries and does not include the same number of columns."},
            {"Manages file operations and is shared on a network.","Manages file operations and is limited to one PC.","Acts as a fat client and is shared on a network.","Acts as a fat client and is limited to one PC."},
            {"True","False","",""},
            {"Used to develop logical schemas","A data definition language for OODB","A method to implement a logical schema","All of the above."}
    };
    public static String correctAnswer[]={
            "COBOL programs",
            "INSERT",
            "True",
            "Commercial courier service",
            "Both A and B.",
            "Very fast",
            "Combines the output from multiple queries and must include the same number of columns.",
            "Manages file operations and is shared on a network.",
            "True",
            "All of the above."
    };
    public static String desAns[]={
            "COBOL programs",
            "INSERT",
            "True",
            "Commercial courier service",
            "Both A and B.",
            "Very fast",
            "Combines the output from multiple queries and must include the same number of columns.",
            "Manages file operations and is shared on a network.",
            "True",
            "All of the above."
    };
}
