package com.example.projectfinal;

public class questionAnswer {
public static String question[] ={
        "Q1. The cost price of 20 articles is the same as the selling price of x articles. If the profit is 25%, then the value of x is:",
        "Q2. In a certain store, the profit is 320% of the cost. If the cost increases by 25% but the selling price remains constant, approximately what percentage of the selling price is the profit?",
        "Q3. A boat can travel with a speed of 13 km/hr in still water. If the speed of the stream is 4 km/hr, find the time taken by the boat to go 68 km downstream.",
        "Q4. In one hour, a boat goes 11 km/hr along the stream and 5 km/hr against the stream. The speed of the boat in still water (in km/hr) is:",
        "Q5. Two ships are sailing in the sea on the two sides of a lighthouse. The angle of elevation of the top of the lighthouse is observed from the ships are 30° and 45° respectively. If the lighthouse is 100 m high, the distance between the two ships is:",
        "Q6. A train running at the speed of 60 km/hr crosses a pole in 9 seconds. What is the length of the train?",
        "Q7. A train 125 m long passes a man, running at 5 km/hr in the same direction in which the train is going, in 10 seconds. The speed of the train is:",
        "Q8. The length of the bridge, which a train 130 metres long and travelling at 45 km/hr can cross in 30 seconds, is:",
        "Q9. Two trains running in opposite directions cross a man standing on the platform in 27 seconds and 17 seconds respectively and they cross each other in 23 seconds. The ratio of their speeds is:",
        "Q10. A train passes a station platform in 36 seconds and a man standing on the platform in 20 seconds. If the speed of the train is 54 km/hr, what is the length of the platform?",
        "Q11. Two trains are moving in opposite directions @ 60 km/hr and 90 km/hr. Their lengths are 1.10 km and 0.9 km respectively. The time taken by the slower train to cross the faster train in seconds is:",
        "Q12. Two trains of equal length are running on parallel lines in the same direction at 46 km/hr and 36 km/hr. The faster train passes the slower train in 36 seconds. The length of each train is:",
        "Q13. A 270 metres long train running at the speed of 120 kmph crosses another train running in opposite direction at the speed of 80 kmph in 9 seconds. What is the length of the other train?",
        "Q14. Two trains, each 100 m long, moving in opposite directions, cross each other in 8 seconds. If one is moving twice as fast the other, then the speed of the faster train is:",
        "Q15. A train 110 metres long is running with a speed of 60 kmph. In what time will it pass a man who is running at 6 kmph in the direction opposite to that in which the train is going?",
        "Q16. A train travelling at a speed of 75 mph enters a tunnel 3*1/2 miles long. The train is 1/4 mile long. How long does it take for the train to pass through the tunnel from the moment the front enters to the moment the rear emerges?",
        "Q17. A train 800 metres long is running at a speed of 78 km/hr. If it crosses a tunnel in 1 minute, then the length of the tunnel (in meters) is:",
        "Q18. A 300 metre long train crosses a platform in 39 seconds while it crosses a signal pole in 18 seconds. What is the length of the platform?",
        "Q19. A train moves past a telegraph post and a bridge 264 m long in 8 seconds and 20 seconds respectively. What is the speed of the train?",
        "Q20. Two goods train each 500 m long, are running in opposite directions on parallel tracks. Their speeds are 45 km/hr and 30 km/hr respectively. Find the time taken by the slower train to pass the driver of the faster one.",
        "Q21. Two trains of equal lengths take 10 seconds and 15 seconds respectively to cross a telegraph post. If the length of each train be 120 metres, in what time (in seconds) will they cross each other travelling in opposite direction?",
        "Q22. A train 108 m long moving at a speed of 50 km/hr crosses a train 112 m long coming from opposite direction in 6 seconds. The speed of the second train is:",
        "Q23. In a flight of 600 km, an aircraft was slowed down due to bad weather. Its average speed for the trip was reduced by 200 km/hr and the time of flight increased by 30 minutes. The duration of the flight is:",
        "Q24. A man complete a journey in 10 hours. He travels first half of the journey at the rate of 21 km/hr and second half at the rate of 24 km/hr. Find the total journey in km.",
        "Q25. The ratio between the speeds of two trains is 7 : 8. If the second train runs 400 km in 4 hours, then the speed of the first train is:",
        "Q26. A car travelling with 5/7 of its actual speed covers 42 km in 1 hr 40 min 48 sec. Find the actual speed of the car.",
        "Q27. In covering a distance of 30 km, Abhay takes 2 hours more than Sameer. If Abhay doubles his speed, then he would take 1 hour less than Sameer. Abhay's speed is:",
        "Q28. Robert is travelling on his cycle and has calculated to reach point A at 2 P.M. if he travels at 10 kmph, he will reach there at 12 noon if he travels at 15 kmph. At what speed must he travel to reach A at 1 P.M.?",
        "Q29. It takes eight hours for a 600 km journey, if 120 km is done by train and the rest by car. It takes 20 minutes more, if 200 km is done by train and the rest by car. The ratio of the speed of the train to that of the cars is:",
        "Q30. A man covered a certain distance at some speed. Had he moved 3 kmph faster, he would have taken 40 minutes less. If he had moved 2 kmph slower, he would have taken 40 minutes more. The distance (in km) is:",
        "Q31. From a point P on a level ground, the angle of elevation of the top tower is 30°. If the tower is 100 m high, the distance of point P from the foot of the tower is:",
        "Q32. A batsman scored 110 runs which included 3 boundaries and 8 sixes. What percent of his total score did he make by running between the wickets?",
        "Q33. Two students appeared at an examination. One of them secured 9 marks more than the other and his marks was 56% of the sum of their marks. The marks obtained by them are:",
        "Q34. A fruit seller had some apples. He sells 40% apples and still has 420 apples. Originally, he had:",
        "Q35. What percentage of numbers from 1 to 70 have 1 or 9 in the unit's digit?",
        "Q36. In a certain school, 20% of students are below 8 years of age. The number of students above 8 years of age is 2/3 of the number of students of 8 years of age which is 48. What is the total number of students in the school?",
        "Q37. Two numbers A and B are such that the sum of 5% of A and 4% of B is two-third of the sum of 6% of A and 8% of B. Find the ratio of A : B.",
        "Q38. A student multiplied a number by 3/5 instead of 5/3. What is the percentage error in the calculation?",
        "Q39. In an election between two candidates, one got 55% of the total valid votes, 20% of the votes were invalid. If the total number of votes was 7500, the number of valid votes that the other candidate got, was:",
        "Q40. Two tailors X and Y are paid a total of Rs. 550 per week by their employer. If X is paid 120 percent of the sum paid to Y, how much is Y paid per week?",
        "Q41. The sum of ages of 5 children born at the intervals of 3 years each is 50 years. What is the age of the youngest child?",
        "Q42. A father said to his son, I was as old as you are at the present at the time of your birth. If the father's age is 38 years now, the son's age five years back was:",
        "Q43. A is two years older than B who is twice as old as C. If the total of the ages of A, B and C be 27, then how old is B?",
        "Q44. Present ages of Sameer and Anand are in the ratio of 5 : 4 respectively. Three years hence, the ratio of their ages will become 11 : 9 respectively. What is Anand's present age in years?",
        "Q45. A man is 24 years older than his son. In two years, his age will be twice the age of his son. The present age of his son is:",
        "Q46. Six years ago, the ratio of the ages of Kunal and Sagar was 6 : 5. Four years hence, the ratio of their ages will be 11 : 10. What is Sagar's age at present?",
        "Q47. The sum of the present ages of a father and his son is 60 years. Six years ago, father's age was five times the age of the son. After 6 years, son's age will be:",
        "Q48. Sachin is younger than Rahul by 7 years. If their ages are in the respective ratio of 7 : 9, how old is Sachin?",
        "Q49. The present ages of three persons in proportions 4 : 7 : 9. Eight years ago, the sum of their ages was 56. Find their present ages (in years).",
        "Q50. Ayesha's father was 38 years of age when she was born while her mother was 36 years old when her brother four years younger to her was born. What is the difference between the ages of her parents?"

};
public static String choices[][]={

        {"16"},
        {"70%"},
        {"4 hours"},
        {"8 KM/hr"},
        {"273 m"},
        {"150 metres"},
        {"50 km/hr"},
        {"245 m"},
        {"3 : 2"},
        {"240 m"},
        {"48"},
        {"50 m"},
        {"230 m"},
        {"60 km/hr"},
        {"6 sec"},
        {"3 min"},
        {"500"},
        {"350m"},
        {"79.2 km/hr"},
        {"24 sec"},
        {"12"},
        {"82 km/hr"},
        {"1 hour"},
        {"224 km"},
        {"87.5 km/hr"},
        {"35 km/hr"},
        {"5 kmph"},
        {"12 kmph"},
        {"3 : 4"},
        {"40"},
        {"173 m"},
        {"45*(5/11)%"},
        {"42, 33"},
        {"700 apples"},
        {"20"},
        {"100"},
        {"4 : 3"},
        {"64%"},
        {"2700"},
        {"Rs. 250"},
        {"4 years"},
        {"14 years"},
        {"10"},
        {"24"},
        {"22 years"},
        {"16 years"},
        {"20 years"},
        {"24.5 years"},
        {"16, 28, 36"},
        {"6 years"}

};


}
