package com.example.projectfinal;

public class si {
    public static String question[] ={
            "Q1. A sum of money at simple interest amounts to Rs. 815 in 3 years and to Rs. 854 in 4 years. The sum is:",
            "Q2. Mr. Thomas invested an amount of Rs. 13,900 divided in two different schemes A and B at the simple interest rate of 14% p.a. and 11% p.a. respectively. If the total amount of simple interest earned in 2 years be Rs. 3508, what was the amount invested in Scheme B?",
            "Q3. A sum fetched a total simple interest of Rs. 4016.25 at the rate of 9 p.c.p.a. in 5 years. What is the sum?",
            "Q4. How much time will it take for an amount of Rs. 450 to yield Rs. 81 as interest at 4.5% per annum of simple interest?",
            "Q5. Reena took a loan of Rs. 1200 with simple interest for as many years as the rate of interest. If she paid Rs. 432 as interest at the end of the loan period, what was the rate of interest?",
            "Q6. A sum of Rs. 12,500 amounts to Rs. 15,500 in 4 years at the rate of simple interest. What is the rate of interest?",
            "Q7. An automobile financier claims to be lending money at simple interest, but he includes the interest every six months for calculating the principal. If he is charging an interest of 10%, the effective rate of interest becomes:",
            "Q8. A lent Rs. 5000 to B for 2 years and Rs. 3000 to C for 4 years on simple interest at the same rate of interest and received Rs. 2200 in all from both of them as interest. The rate of interest per annum is:",
            "Q9. A sum of Rs. 725 is lent in the beginning of a year at a certain rate of interest. After 8 months, a sum of Rs. 362.50 more is lent but at the rate twice the former. At the end of the year, Rs. 33.50 is earned as interest from both the loans. What was the original rate of interest?",
            "Q10. A man took loan from a bank at the rate of 12% p.a. simple interest. After 3 years he had to pay Rs. 5400 interest only for the period. The principal amount borrowed by him was:",
            "Q11. A sum of money amounts to Rs. 9800 after 5 years and Rs. 12005 after 8 years at the same rate of simple interest. The rate of interest per annum is:",
            "Q12. What will be the ratio of simple interest earned by certain amount at the same rate of interest for 6 years and that for 9 years?",
            "Q13. A certain amount earns simple interest of Rs. 1750 after 7 years. Had the interest been 2% more, how much more interest would it have earned?",
            "Q14. A person borrows Rs. 5000 for 2 years at 4% p.a. simple interest. He immediately lends it to another person at 6(1/4)% p.a for 2 years. Find his gain in the transaction per year",
            "Q15. A bank offers 5% compound interest calculated on half-yearly basis. A customer deposits Rs. 1600 each on 1st January and 1st July of a year. At the end of the year, the amount he would have gained by way of interest is:",
            "Q16. The difference between simple and compound interests compounded annually on a certain sum of money for 2 years at 4% per annum is Re. 1. The sum (in Rs.) is:",
            "Q17. There is 60% increase in an amount in 6 years at simple interest. What will be the compound interest of Rs. 12,000 after 3 years at the same rate?",
            "Q18. What is the difference between the compound interests on Rs. 5000 for 1(1/2) years at 4% per annum compounded yearly and half-yearly?",
            "Q19. The compound interest on Rs. 30,000 at 7% per annum is Rs. 4347. The period (in years) is:",
            "Q20. What will be the compound interest on a sum of Rs. 25,000 after 3 years at the rate of 12 p.c.p.a.?",
            "Q21. At what rate of compound interest per annum will a sum of Rs. 1200 become Rs. 1348.32 in 2 years?",
            "Q22. The least number of complete years in which a sum of money put out at 20% compound interest will be more than doubled is:",
            "Q23. Albert invested an amount of Rs. 8000 in a fixed deposit scheme for 2 years at compound interest rate 5 p.c.p.a. How much amount will Albert get on maturity of the fixed deposit?",
            "Q24. The effective annual rate of interest corresponding to a nominal rate of 6% per annum payable half-yearly is:",
            "Q25. Simple interest on a certain sum of money for 3 years at 8% per annum is half the compound interest on Rs. 4000 for 2 years at 10% per annum. The sum placed on simple interest is:"
    };
    public static String choices[][]={
            {"Rs. 650","Rs. 690","Rs. 698","Rs. 700"},
            {"Rs. 6400","Rs. 6500","Rs. 7200","Rs. 7500"},
            {"Rs. 4462.50","Rs. 8032.50","Rs. 8900","Rs. 8925"},
            {"3.5 years","4 years","4.5 years","5 years"},
            {"3.6","6","18","Cannot be determined"},
            {"3%","4%","5%","6%"},
            {"10%","10.25%","10.5%","None of these"},
            {"5%","7%","8%","10%"},
            {"3.6%","4.5%","5%","3.46%"},
            {"Rs. 2000","Rs. 10,000","Rs. 15,000","Rs. 20,000"},
            {"5%","8%","12%","15%"},
            {"1 : 3","1 : 4","2 : 3","Data inadequate"},
            {"Rs. 35","Rs. 245","Rs. 350","Cannot be determined"},
            {"Rs. 112.50","Rs. 125","Rs. 225","Rs. 167.50"},
            {"Rs. 120","Rs. 121","Rs. 122","Rs. 123"},
            {"625","630","640","650"},
            {"Rs. 2160","Rs. 3120","Rs. 3972","Rs. 6240"},
            {"Rs. 2.04","Rs. 3.06","Rs. 4.80","Rs. 8.30"},
            {"2","2(1/2)","3","4"},
            {"Rs. 9000.30","Rs. 9720","Rs. 10123.20","Rs. 10483.20"},
            {"6%","6.5%","7%","7.5%"},
            {"3","4","5","6"},
            {"Rs. 8600","Rs. 8620","Rs. 8820",""},
            {"6.06%","6.07%","6.08%","6.09%"},
            {"Rs. 1550","Rs. 1650","Rs. 1750","Rs. 2000"}
    };
    public static String correctAnswer[]={
            "Rs. 698",
            "Rs. 6400",
            "Rs. 8925",
            "4 years",
            "6",
            "6%",
            "10.25%",
            "10%",
            "3.46%",
            "Rs. 15,000",
            "12%",
            "2 : 3",
            "Cannot be determined",
            "Rs. 112.50",
            "Rs. 121",
            "625",
            "Rs. 3972",
            "Rs. 2.04",
            "2",
            "Rs. 10123.20",
            "6%",
            "4",
            "Rs. 8820",
            "6.09%",
            "Rs. 1750"
    };
}
